WHITESPACE = WS_OR_COMMS MORE_WS_OR_COMMS
WS_OR_COMMS = SYM_WHITESPACE | SYM_SLINE_COMMENT | SYM_MLINE_COMMENT 
MORE_WS_OR_COMMS = (WS_OR_COMMS MORE_WS_OR_COMMS) | ε

SYM_WHITESPACE = #"\s+"
SYM_SLINE_COMMENT = #"//.*"
SYM_MLINE_COMMENT = #"(?s)/\*.*\*/"